apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    jsonData:
      maxQueryLookback: "24h"
      timeout: 60
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id"
          matcherType: label
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"
